const style = {
  paddingNone: { padding: 0 },
  tabPanel: {
    background: "white",
    width: "100%",
    borderRadius: { xs: "0 4px 4px 4px", sm: "4px 0 4px 4px" },
    border: "1px solid #00000033",
    marginLeft: { xs: "-1px", sm: 0 },
    marginTop: { xs: 0, sm: "-1px" },
  },
  tabPanelChildren: { px: 4, py: 8 },
  stylistCaption: { fontWeight: 500, color: "#6C6C6C" },
  stylistHeading: { fontWeight: 500, color: "#3C4242", textAlign: "center" },
  stylistContainer: {
    overflow: "auto",
    maxWidth: {
      xs: "100%",
      sm: "55px",
    },
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  homeDivider: { height: "70%", margin: "auto", maxWidth: "100%" },
  descWidth: { maxWidth: "450px" },
  centerText: { textAlign: "center" },
  para: { fontWeight: 400, mt: 1.5, textAlign: "center" },
  descButton: {
    paddingY: 2,
    paddingX: { sm: 1, md: 3 },
    backgroundColor: "primary.dark",
  },
  descButtonTitle: {
    fontFamily: "praise",
    fontWeight: 400,
    textTransform: "initial",
  },
  descButtonPara: {
    fontFamily: "Outfit",
    mt: -1,
    textTransform: "lowercase",
    fontWeight: 400,
  },
  link: { fontWeight: 400, color: "#868686" },
  joinBtn: { background: "#F0F0F0", px: 2 },
  dividerWidth: { width: "70%" },
  loginInputBg: { background: "#F4F4F4" },
  dividerValue: {
    opacity: 0.8,
    fontSize: "10px",
    position: "absolute",
    top: -8,
  },
  dashedDividerBoxStyle: {
    px: 1.4,
    height: "18px",
    borderRadius: "10px",
    alignItems: "center",
    justifyContent: "center",
  },
  dashedDividerStyle: {
    border: "1px dashed",
    borderColor: "primary.main",
    width: "100%",
    position: "relative",
    "&::before": {
      content: '""',
      height: "6px",
      width: "2px",
      bgcolor: "primary.main",
      position: "absolute",
      top: "50%",
      left: "-5px",
      transform: "translateY(-50%)",
    },
    "&::after": {
      content: '""',
      height: "6px",
      width: "2px",
      bgcolor: "primary.main", // Color for the round end caps
      position: "absolute",
      top: "50%",
      right: "-5px",
      transform: "translateY(-50%)",
    },
  },
  relativePostion: { position: "relative" },
  sizerImage: { position: "relative", width: "145" },
  fullWidth: { width: "100%" },
  sizerTitle: { color: "black", textAlign: "center", mb: 2, fontWeight: 500 },
  leftSliderLabel: { mr: -4, color: "#868686", fontWeight: 400 },
  rightSliderLabel: { ml: -7, color: "#868686", fontWeight: 400 },
  mainSlider: {
    mt: 2,
    ".MuiSlider-rail": {
      color: "#00000000",
    },
    "&::after": {
      content: '""',
      width: "3px",
      left: "-7px",
      height: "8px",
      borderRadius: "5px",
      bgcolor: "primary.main",
      position: "absolute",
      top: "50%",
      transform: "translateY(-50%)",
    },
    "&::before": {
      content: '""',
      width: "3px",
      right: "-7px",
      height: "8px",
      borderRadius: "5px",
      bgcolor: "primary.main",
      position: "absolute",
      top: "50%",
      transform: "translateY(-50%)",
    },
  },
  sliderTitle: { fontWeight: 400, textAlign: "center", color: "#020202" },
  sliderWidth: { maxWidth: "500px", width: "100%" },
  displayFlex: { display: "flex !important" },
  tabPanelBackground: {
    background: "#FAFAFA",
    width: "100%",
    borderRadius: "10px",
  },
  wrap: { flexWrap: "wrap" },
  favouriteStyleHead: {
    fontWeight: 400,
    textAlign: "center",
    color: "#020202",
  },
  lookBtn: { color: "black", fontWeight: 400, textTransform: "lowercase" },
  lookBtnHead: { fontWeight: 600, textTransform: "initial" },
  loginBtn: { paddingX: 4, paddingY: 1 },
  colorPrimaryLight: {
    color: "primary.light",
  },
  bgWhite: { background: "white" },
  selectLabel: { color: "black", fontWeight: 500 },
  selectBox: {
    position: "absolute",
    minWidth: 120,
    background: "#F7F7F7",
    p: 0.6,
    pt: 0,
    borderRadius: 0.5,
  },
};

export default style;
